config/routes.rb
Rails.application.routes.draw do
  mount PgHero::Engine, at: "pghero"
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: "management_module/settings/employee_registrations" }
  devise_for :member_accounts, controllers: { sessions: 'member_accounts/sessions', registrations: "member_accounts/registrations" }

  authenticated :user do
    root :to => 'accounting_module/accounts#index', :constraints => lambda { |request| request.env['warden'].user.role == 'accountant' if request.env['warden'].user }, as: :accounting_module_root
    root :to => 'accounting_module/reports/ticket_entries#index', :constraints => lambda { |request| request.env['warden'].user.role == 'bookkeeper' if request.env['warden'].user }, as: :bookkeeper_root

    root :to => 'loans#index', :constraints => lambda { |request| request.env['warden'].user.role == 'loan_officer' if request.env['warden'].user }, as: :loan_officer_root
    root :to => 'treasury_module/cash_accounts#index', :constraints => lambda { |request| request.env['warden'].user.role == 'teller' if request.env['warden'].user }, as: :teller_root
    root :to => 'members#index', :constraints => lambda { |request| request.env['warden'].user.role == 'general_manager' if request.env['warden'].user }, as: :general_manager_root
    root :to => 'members#index', :constraints => lambda { |request| request.env['warden'].user.role == 'branch_manager' if request.env['warden'].user }, as: :branch_manager_root
    root :to => 'members#index', :constraints => lambda { |request| request.env['warden'].user.role == 'treasurer' if request.env['warden'].user }, as: :treasurer_root

    root :to => 'store_front_module/line_items/sales_line_items#new', :constraints => lambda { |request| request.env['warden'].user.role == 'sales_clerk' if request.env['warden'].user }, as: :sales_clerk_root
  end
  resources :home, only: [:index]

  resources :accounting_module, only: [:index]
  namespace :accounting_module do
    resources :income_statement_dashboards, only: [:index],module: :dashboards
    resources :assets_dashboards, only: [:index],module: :dashboards

    resources :grand_parent_account_categories, only: [:index, :new, :create]
    resources :general_ledgers,    only: [:index]
    resources :subsidiary_ledgers, only: [:index]

    resources :account_categories, only: [:index, :new, :create, :edit, :update], module: :settings do
      resources :account_sub_categories, only: [:new, :create]
    end

    resources :account_categories, only: [:show] do
      resources :entries,        only: [:index], module: :account_categories
      resources :sub_categories, only: [:index], module: :account_categories
      resources :settings,       only: [:index], module: :account_categories
      resources :accounts,       only: [:index], module: :account_categories
    end

    resources :settings, only: [:index]
    resources :amounts, only: [:destroy]
    resources :commercial_document_adjusting_entry_line_items, only: [:new, :create, :destroy], module: :entries
    resources :per_employee_entries, only: [:index], module: :entries
    resources :per_office_entries, only: [:index], module: :entries
    resources :scheduled_entries, only: [:index]
    resources :interest_expense_vouchers, only: [:show]
    namespace :scheduled_entries do
      resources :savings_accounts_interest_postings, only: [:index, :new, :create]
      resources :share_capital_dividend_postings, only: [:new, :create]
    end

    namespace :cash_books do
      resources :cash_receipts,                       only: [:index]
      resources :cash_disbursements,                  only: [:index]
    end

    resources :cash_receipts,           module: :entries,     only: [:index]
    resources :cash_disbursements,      module: :entries, only: [:index]
    resources :journal_entry_vouchers,  module: :entries, only: [:index]

    resources :entry_line_item_vouchers, only: [:create, :show, :destroy], module: :entries do
      resources :confirmations, only: [:create], module: :entry_line_item_vouchers
    end

    resources :interests_earned_postings, only: [:create]
    resources :entry_line_items, only: [:new, :create, :destroy]
    resources :entry_processings, only: [:create]
    resources :financial_condition_comparisons, only: [:new, :create, :show]
    resources :reports, only: [:index]

    namespace :reports do
      resources :equity_changes_statements, only: [:index]
      resources :cash_receipts, only: [:index]
      resources :cash_disbursements, only: [:index]
      resources :journal_entries, only: [:index]
      resources :entries, only: [:index]


      namespace :cashbooks do
        resources :cash_receipts,      only: [:index]
        resources :cash_disbursements, only: [:index]
      end
      resources :entries, only: [:index]
      resources :net_income_distributions, only: [:index]
      resources :trial_balances,           only: [:index]
      resources :ticket_entries,           only: [:index]

      resources :proofsheets,              only: [:index]
      resources :income_statements,        only: [:index]
      resources :balance_sheets,           only: [:index]
      resources :financial_conditions,     only: [:index]
      resources :cash_books,               only: [:index]
    end

    resources :settings, only: [:index]

    resources :accounts, except: [:destroy] do
      resources :account_categories,  only: [:new, :create], module: :accounts

      resources :reports,             only: [:index], module: :accounts
      resources :settings,            only: [:index], module: :accounts
      resources :entries,             only: [:index], module: :accounts
    end

    resources :assets, controller: 'accounts', type: 'AccountingModule::Asset'

    resources :entries do
      resources :cancellations, only: [:new, :create], module: :entries
    end

    resources :debit_amounts, only: [:edit, :update]
    resources :credit_amounts, only: [:edit, :update]

  end

  resources :loans_module, only: [:index]

  namespace :loans_module do
    resources :loan_groups, only: [:new, :create], module: :settings
    resources :loan_application_product_selections, only: [:new]
    resources :interest_calculation_selections, only: [:new]
    resources :amortization_schedules, only: [:index, :show]
    resources :amortization_schedule_date_filters, only: [:index]

    resources :organizations, only: [:index, :show] do
      resources :loans, only: [:index], module: :organizations
      resources :reports, only: [:index], module: :organizations
    end

    resources :archived_loans, only: [:index]
    resources :disbursement_vouchers, only: [:create]

    namespace :monitoring do
      resources :metrics, only: [:index]
    end

    resources :search_results, only: [:index]

    namespace :reports do
      resources :loan_agings,                    only: [:index]
      resources :loan_agings_summaries,          only: [:index]
      resources :loan_agings_by_loan_products,   only: [:index]
      resources :loan_agings_by_barangays,       only: [:index]
      resources :loan_maturities,                only: [:index]
      resources :loan_releases,                  only: [:index]
      resources :loan_releases_by_loan_products, only: [:index]
      resources :loan_releases_by_barangays,     only: [:index]
      resources :loan_releases_summaries,        only: [:index]



      resources :loan_collections, only: [:index]
      resources :loan_collections_summaries, only: [:index]

      resources :aging_loans, only: [:index]
    end

    resources :member_borrowers, only: [:index, :show]
    resources :reports, only: [:index]
    resources :aging_loans, only: [:index, :show]

    resources :loan_applications, only: [:index, :new, :create, :show, :destroy] do
      resources :guarantors,             only: [:new, :create], module: :loan_applications
      resources :share_capital_openings, only: [:new, :create], module: :loan_applications
      resources :savings_account_openings, only: [:new, :create], module: :loan_applications

      resources :disbursements,                       only: [:new, :create],                           module: :loan_applications
      resources :capital_build_up_processings,        only: [:new, :create],                           module: :loan_applications
      resources :savings_account_deposit_processings, only: [:new, :create],                           module: :loan_applications
      resources :previous_loan_payment_processings,   only: [:new, :create],                           module: :loan_applications
      resources :vouchers,                            only: [:new, :create, :show, :destroy],          module: :loan_applications do
        resources :disbursements, only: [:new, :create]
      end
      resources :amortization_schedules,              only: [:index],                                  module: :loan_applications
      resources :voucher_confirmations,               only: [:create],                                 module: :loan_applications
      resources :loan_amounts,                        only: [:new, :create],                           module: :loan_applications
      resources :voucher_amounts,                     only: [:new, :create, :edit, :update, :destroy], module: :loan_applications
      resources :voucher_credit_amounts,                     only: [:new, :create, :edit, :update, :destroy], module: :loan_applications

      resources :program_subscription_payments,       only: [:new, :create], module: :loan_applications
      resources :program_subscriptions,       only: [:new, :create], module: :loan_applications
    end

    resources :dashboard, only: [:index]

    resources :loan_products, only:[:index, :show] do
      resources :insights, only: [:index], module: :loan_products
      resources :loans, only: [:index], module: :loan_products
      resources :reports, only: [:index], module: :loan_products
    end

app/controllers/accounting_module/accounts/reports_controller.rb
module AccountingModule
  module Accounts
    class ReportsController < ApplicationController
      def index
        @account = current_office.accounts.find(params[:account_id])
      end
    end
  end
end

app/controllers/accounting_module/reports/balance_sheets_controller.rb
module AccountingModule
  module Reports
    class BalanceSheetsController < ApplicationController
      def index
        first_entry = current_cooperative.entries.order('entry_date ASC').first
        @from_date  = first_entry ? DateTime.parse(first_entry.entry_date.strftime("%B %e, %Y")) : Time.zone.now
        @to_date    = params[:to_date] ? DateTime.parse(params[:to_date]) : Time.zone.now
        @office     = params[:office_id] ? current_cooperative.offices.find(params[:office_id]) : current_office
        @cooperative = current_cooperative
        respond_to do |format|
          format.xlsx
          format.html # index.html.erb
          format.pdf do
            pdf = AccountingModule::Reports::BalanceSheetPdf.new(
              from_date:    @from_date,
              to_date:      @to_date,
              view_context: view_context,
              office:       @office,
              cooperative:  current_cooperative)
            send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Balance Sheet.pdf"
          end
        end
      end
    end
  end
end

app/controllers/accounting_module/reports/cash_disbursements_controller.rb
module AccountingModule
  module Reports
    class CashDisbursementsController < ApplicationController
      def index
        @from_date = params[:from_date] ? Date.parse(params[:from_date]) : Date.current
        @to_date   = params[:to_date] ? Date.parse(params[:to_date]) : Date.current
        @cash_account = params[:cash_account_id] ? current_cooperative.cash_accounts.find(params[:cash_account_id]) : current_cooperative.cash_accounts.first

        if params[:from_date] && params[:to_date]
          @pagy, @entries = pagy(@cash_account.credit_entries.includes(:commercial_document, :recorder).entered_on(from_date: @from_date, to_date: @to_date))
        else
          @pagy, @entries = pagy(@cash_account.credit_entries.includes(:commercial_document, :recorder))
        end
      end
    end
  end
end

app/controllers/accounting_module/reports/cash_receipts_controller.rb
module AccountingModule
  module Reports
    class CashReceiptsController < ApplicationController
      def index
        @from_date = params[:from_date] ? Date.parse(params[:from_date]) : Date.current
        @to_date   = params[:to_date] ? Date.parse(params[:to_date]) : Date.current
        @cash_account = params[:cash_account_id] ? current_cooperative.cash_accounts.find(params[:cash_account_id]) : current_cooperative.cash_accounts.first

        if params[:from_date] && params[:to_date]
          @pagy, @entries = pagy(@cash_account.debit_entries.includes(:commercial_document, :recorder).entered_on(from_date: @from_date, to_date: @to_date))
        else
          @pagy, @entries = pagy(@cash_account.debit_entries.includes(:commercial_document, :recorder))
        end
      end
    end
  end
end

app/controllers/accounting_module/reports/cashbooks/cash_disbursements_controller.rb
module AccountingModule
  module Reports
    module Cashbooks
      class CashDisbursementsController < ApplicationController
        def index
          @cooperative_service = params[:cooperative_service_id].present? ? current_cooperative.cooperative_services.find(params[:cooperative_service_id]) : nil
          if params[:from_date].present? && params[:to_date].present?
            @from_date = params[:from_date] ? DateTime.parse(params[:from_date]) : current_cooperative.entries.order(entry_date: :asc).first.entry_date
            @to_date = params[:to_date] ? DateTime.parse(params[:to_date]) : Date.today.end_of_year
            @entries_for_pdf = current_cooperative.cash_accounts.credit_entries.where(cooperative_service_id: params[:cooperative_service_id]).entered_on(from_date: @from_date, to_date: @to_date)
            @ordered_entries = current_cooperative.cash_accounts.credit_entries.order(reference_number: :desc).where(cooperative_service_id: params[:cooperative_service_id]).entered_on(from_date: @from_date, to_date: @to_date)
            @entries = @ordered_entries.paginate(:page => params[:page], :per_page => 50)

          elsif params[:organization_id].present? && params[:search].present?
            @organization = current_cooperative.organizations.find(params[:organization_id])
            @entries_for_pdf = @organization.member_entries.text_search(params[:search])
            if @entries_for_pdf.present?
              @from_date = @organization.member_entries.order(entry_date: :asc).first.entry_date
              @to_date = @organization.member_entries.order(entry_date: :desc).first.entry_date
            end
            @ordered_entries = @organization.member_entries.order(reference_number: :desc).text_search(params[:search])
            @entries = @ordered_entries.paginate(:page => params[:page], :per_page => 50)
            
          elsif params[:organization_id].blank? && params[:search].present?
            @entries_for_pdf = current_cooperative.entries.text_search(params[:search])
            if @entries_for_pdf.present?
              @from_date = @entries_for_pdf.order(entry_date: :asc).first.entry_date
              @to_date = @entries_for_pdf.order(entry_date: :desc).first.entry_date
            end
            @ordered_entries = current_cooperative.entries.order(reference_number: :desc).text_search(params[:search])
            @entries = @ordered_entries.paginate(:page => params[:page], :per_page => 50)

          elsif params[:recorder_id].present?
            @recorder = current_cooperative.users.find(params[:recorder_id])
            @entries_for_pdf = @recorder.cash_accounts.credit_entries
            if @entries_for_pdf.present?
              @from_date = @entries_for_pdf.order(entry_date: :asc).first.entry_date
              @to_date = @entries_for_pdf.order(entry_date: :desc).first.entry_date
            end
            @ordered_entries = @recorder.cash_accounts.credit_entries.order(reference_number: :desc)
            @entries = @ordered_entries.paginate(:page => params[:page], :per_page => 50)
          
          else
            @from_date = params[:from_date] ? DateTime.parse(params[:from_date]) : current_cooperative.entries.order(entry_date: :asc).first.entry_date
            @to_date = params[:to_date] ? DateTime.parse(params[:to_date]) : Date.today.end_of_year
            @entries_for_pdf = current_cooperative.cash_accounts.credit_entries.where(cooperative_service_id: params[:cooperative_service_id])
            @ordered_entries = current_cooperative.cash_accounts.credit_entries.where(cooperative_service_id: params[:cooperative_service_id]).order(reference_number: :desc)
            @entries = @ordered_entries.paginate(page: params[:page], per_page:  50)
          end
          respond_to do |format|
            format.html
            format.xlsx
            format.pdf do
              pdf = AccountingModule::CashBooks::CashDisbursementsPdf.new(
                from_date:    @from_date,
                to_date:      @to_date,
                entries:      @entries_for_pdf,
                cooperative_service: @cooperative_service,
                employee:     current_user,
                title: "Cash Disbursement Vouchers",
                view_context: view_context)
              send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Entries report.pdf"
            end
          end
        end
      end
    end
  end
end

app/views/accounting_module/reports/trial_balances/index.html.erb
<div class="card">
  <div class="card-header">
    <div class="row">
      <div class="col-md-9">
        <h3 class="card-title">Trial Balance </h3>
        <p class="text-muted"> Date Covered: <%= @from_date.strftime("%B %e, %Y") %> - <%= @to_date.strftime("%B %e, %Y") %></p>
      </div>
      <div class="col-md-3">
        <%= link_to 'Excel', accounting_module_reports_trial_balances_path(format: 'xlsx', from_date: @from_date, to_date: @to_date) %>
        <%= link_to 'PDF', accounting_module_reports_trial_balances_path(format: 'pdf', from_date: @from_date, to_date: @to_date) %>

      </div>
    </div>
  </div>
  <div class="card-body">
    <%= form_tag({:action => "index", controller: "accounting_module/reports/trial_balances", to_date: params[:to_date]}, {:method => :get})  do %>
       <div class="row">
         <div class="col-md-3">
           <div class="form-group">
             <%= text_field_tag :from_date, @from_date.strftime("%B %e, %Y"), :class => 'form-control border-input datepicker', :placeholder => "To " %>
           </div>
         </div>
         <div class="col-md-3">
           <div class="form-group">
             <%= text_field_tag :to_date, @to_date.strftime("%B %e, %Y"), :class => 'form-control border-input datepicker', :placeholder => "To " %>
           </div>
         </div>
         <div class="col-md-1">
           <button type="submit" class="btn btn-primary"> Generate</button>
         </div>
       </div>
     <% end %>
  <hr>

<div class="row">
  <div class="col-md-4">
    <b> Account </b>
  </div>
  <div class="col-md-2">
    <b> Beginning Balance </b>
  </div>
  <div class="col-md-2">
    <b> Debit </b>
  </div>
  <div class="col-md-2">
    <b> Credit </b>
  </div>
  <div class="col-md-2">
    <b> Ending Balance </b>
  </div>
</div>
<br>
<b> ASSETS </b><br>
<% current_cooperative.grand_parent_account_categories.assets.order(code: :asc).each do |grand_parent_account_category| %>
  <%= grand_parent_account_category.title %>
  <br>
  <% grand_parent_account_category.parent_account_categories.where(office: current_office).order(code: :asc).each do |parent_account_category| %>
    &nbsp; &nbsp; <%= parent_account_category.title %><br>
    <% parent_account_category.parent_account_sub_categories.where(office: current_office).order(code: :asc).each do |parent_account_sub_category| %>
      &nbsp; &nbsp; &nbsp; &nbsp;<%= parent_account_sub_category.title %><br>
      <% parent_account_sub_category.account_categories.where(office: current_office).order(code: :asc).each do |account_category| %>
        <div class="row">
          <div class="col-md-4">
            &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <%= account_category.title %>
          </div>
          <div class="col-md-2">
            <%= number_to_currency account_category.balance(to_date: @from_date) %>
          </div>
          <div class="col-md-2">
            <%= number_to_currency account_category.debits_balance(from_date: @from_date, to_date: @to_date) %>
          </div>
          <div class="col-md-2">
            <%= number_to_currency account_category.credits_balance(from_date: @from_date, to_date: @to_date) %>
          </div>
          <div class="col-md-2">
            <%= number_to_currency account_category.balance(to_date: @to_date) %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>
<hr>
<b> LIABILITIES</b><br>
<% current_cooperative.grand_parent_account_categories.liabilities.order(code: :asc).each do |grand_parent_account_category| %>
  <%= grand_parent_account_category.title %>
  <br>
  <% grand_parent_account_category.parent_account_categories.where(office: current_office).order(code: :asc).each do |parent_account_category| %>
    &nbsp; &nbsp; <%= parent_account_category.title %><br>
    <% parent_account_category.parent_account_sub_categories.where(office: current_office).order(code: :asc).each do |parent_account_sub_category| %>
      &nbsp; &nbsp; &nbsp; &nbsp;<%= parent_account_sub_category.title %><br>
      <% parent_account_sub_category.account_categories.where(office: current_office).order(code: :asc).each do |account_category| %>
        <div class="row">
          <div class="col-md-4">
            &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <%= account_category.title %>
          </div>
          <div class="col-md-2">
            <%= number_to_currency account_category.balance(to_date: @from_date) %>
          </div>
          <div class="col-md-2">
            <%= number_to_currency account_category.debits_balance(from_date: @from_date, to_date: @to_date) %>
          </div>
          <div class="col-md-2">
            <%= number_to_currency account_category.credits_balance(from_date: @from_date, to_date: @to_date) %>
          </div>
          <div class="col-md-2">
            <%= number_to_currency account_category.balance(to_date: @to_date) %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>
<hr>
<b> EQUITY</b><br>
<% current_cooperative.grand_parent_account_categories.equities.order(code: :asc).each do |grand_parent_account_category| %>
  <%= grand_parent_account_category.title %>
  <br>
  <% grand_parent_account_category.parent_account_categories.where(office: current_office).order(code: :asc).each do |parent_account_category| %>
    &nbsp; &nbsp; <%= parent_account_category.title %><br>
    <% parent_account_category.parent_account_sub_categories.where(office: current_office).order(code: :asc).each do |parent_account_sub_category| %>
      &nbsp; &nbsp; &nbsp; &nbsp;<%= parent_account_sub_category.title %><br>
      <% parent_account_sub_category.account_categories.where(office: current_office).order(code: :asc).each do |account_category| %>
        <div class="row">
          <div class="col-md-4">
            &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <%= account_category.title %>
          </div>
          <div class="col-md-2">
            <%= number_to_currency account_category.balance(to_date: @from_date) %>
          </div>
          <div class="col-md-2">
            <%= number_to_currency account_category.debits_balance(from_date: @from_date, to_date: @to_date) %>
          </div>
          <div class="col-md-2">
            <%= number_to_currency account_category.credits_balance(from_date: @from_date, to_date: @to_date) %>
          </div>
          <div class="col-md-2">
            <%= number_to_currency account_category.balance(to_date: @to_date) %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>
<hr>
<b> REVENUE</b><br>
<% current_cooperative.grand_parent_account_categories.revenues.order(code: :asc).each do |grand_parent_account_category| %>
  <%= grand_parent_account_category.title %>
  <br>
  <% grand_parent_account_category.parent_account_categories.where(office: current_office).order(code: :asc).each do |parent_account_category| %>
    &nbsp; &nbsp; <%= parent_account_category.title %><br>
    <% parent_account_category.parent_account_sub_categories.where(office: current_office).order(code: :asc).each do |parent_account_sub_category| %>
      &nbsp; &nbsp; &nbsp; &nbsp;<%= parent_account_sub_category.title %><br>
      <% parent_account_sub_category.account_categories.where(office: current_office).order(code: :asc).each do |account_category| %>
        <div class="row">
          <div class="col-md-4">
            &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <%= account_category.title %>
          </div>
          <div class="col-md-2">
            <%= number_to_currency account_category.balance(to_date: @from_date) %>
          </div>
          <div class="col-md-2">
            <%= number_to_currency account_category.debits_balance(from_date: @from_date, to_date: @to_date) %>
          </div>
          <div class="col-md-2">
            <%= number_to_currency account_category.credits_balance(from_date: @from_date, to_date: @to_date) %>
          </div>
          <div class="col-md-2">
            <%= number_to_currency account_category.balance(to_date: @to_date) %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<hr>
<b> EXPENSES</b><br>
<% current_cooperative.grand_parent_account_categories.expenses.order(code: :asc).each do |grand_parent_account_category| %>
  <%= grand_parent_account_category.title %>
  <br>
  <% grand_parent_account_category.parent_account_categories.where(office: current_office).order(code: :asc).each do |parent_account_category| %>
    &nbsp; &nbsp; <%= parent_account_category.title %><br>
    <% parent_account_category.parent_account_sub_categories.where(office: current_office).order(code: :asc).each do |parent_account_sub_category| %>
      &nbsp; &nbsp; &nbsp; &nbsp;<%= parent_account_sub_category.title %><br>
      <% parent_account_sub_category.account_categories.where(office: current_office).order(code: :asc).each do |account_category| %>
        <div class="row">
          <div class="col-md-4">
            &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <%= account_category.title %>
          </div>
          <div class="col-md-2">
            <%= number_to_currency account_category.balance(to_date: @from_date) %>
          </div>
          <div class="col-md-2">
            <%= number_to_currency account_category.debits_balance(from_date: @from_date, to_date: @to_date) %>
          </div>
          <div class="col-md-2">
            <%= number_to_currency account_category.credits_balance(from_date: @from_date, to_date: @to_date) %>
          </div>
          <div class="col-md-2">
            <%= number_to_currency account_category.balance(to_date: @to_date) %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>
<hr>
<div class="row">
  <div class="col-md-4">

  </div>
  <div class="col-md-2">
    <%= number_to_currency current_cooperative.grand_parent_account_categories.balance(to_date: @from_date) %>
  </div>
  <div class="col-md-2">
    <%= number_to_currency current_cooperative.grand_parent_account_categories.debits_balance(from_date: @from_date, to_date: @to_date) %>

  </div>
  <div class="col-md-2">
    <%= number_to_currency current_cooperative.grand_parent_account_categories.credits_balance(from_date: @from_date, to_date: @to_date) %>

  </div>
  <div class="col-md-2">
    <%= number_to_currency current_cooperative.grand_parent_account_categories.balance(to_date: @to_date) %>
  </div>
</div>